// lib/scripts/seed-products.ts
// Run with: npx ts-node --project tsconfig.json -e "require('./lib/scripts/seed-products.ts')"
// Or add to package.json: "seed": "ts-node lib/scripts/seed-products.ts"

const dotenv = require("dotenv");
const path = require("path");
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

import mongoose from "mongoose";



// ── Config ────────────────────────────────────────────────────────────────────
const MONGODB_URI = process.env.MONGODB_URI!;

// Your real category IDs from DB
const CATEGORIES = {
  "sustainable-shopping":    "69ae7001535bc9abecb6bb31",
  "organic-products-online": "69ae7001535bc9abecb6bb28",
  "organic-food-online":     "69ae7001535bc9abecb6bb2d",
  "chemical-free-products":  "69ae7001535bc9abecb6bb30",
  "artisan-products":        "69ae7001535bc9abecb6bb2f",
  "eco-friendly-products":   "69ae7001535bc9abecb6bb2c",
  "natural-products":        "69ae7001535bc9abecb6bb2b",
  "handmade-crafts":         "69ae7001535bc9abecb6bb2e",
  "handmade-products":       "69ae7001535bc9abecb6bb29",
};

// Use existing shop IDs from your DB
const SHOPS = {
  bhavya:  "69a7e51a8967d5c3d9e8961d",   // Bhavya ki Dukan
  varun:   "6996a7fdfdcbb4173e7f46cd",    // Varun Ki Dukan
  mihir:   "6996dde8fdcbb4173e7f4a10",    // Mihir ki Dukan
};

// Placeholder images (free Unsplash URLs)
const IMAGES = {
  tote:        "https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?w=600",
  bamboo:      "https://images.unsplash.com/photo-1610552050890-fe99536c2615?w=600",
  seedKit:     "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
  orgSerum:    "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600",
  orgFace:     "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600",
  herbShampoo: "https://images.unsplash.com/photo-1585232350473-21a0e2c4a571?w=600",
  honey:       "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600",
  spices:      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600",
  tea:         "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600",
  ghee:        "https://images.unsplash.com/photo-1631452180519-e0e4be9e8d9e?w=600",
  cleanser:    "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600",
  toothpaste:  "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600",
  deodorant:   "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=600",
  pottery:     "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600",
  blockPrint:  "https://images.unsplash.com/photo-1599598425947-5202edd56bdb?w=600",
  woodArt:     "https://images.unsplash.com/photo-1609372332255-611485350f25?w=600",
  jute:        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
  bambooStraw: "https://images.unsplash.com/photo-1611735341450-74d61e660ad2?w=600",
  soapBar:     "https://images.unsplash.com/photo-1600857544200-b2f468e9b2c6?w=600",
  essOil:      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600",
  aloeVera:    "https://images.unsplash.com/photo-1596178060810-72c7ee5b4e9d?w=600",
  candle:      "https://images.unsplash.com/photo-1602607144568-e4a4d9e8e28b?w=600",
  macrame:     "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
  jewelry:     "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600",
  embroidery:  "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
};

// ── Products ──────────────────────────────────────────────────────────────────
const SEED_PRODUCTS = [

  // ── 1. Sustainable Shopping (5 products) ────────────────────────────────────
  {
    name: "Organic Cotton Tote Bag",
    slug: "organic-cotton-tote-bag",
    description: "100% organic cotton tote bag — durable, washable, and perfect for everyday shopping. Replace plastic bags with this eco-conscious choice.",
    price: 349,
    discountPrice: 249,
    image: IMAGES.tote,
    images: [IMAGES.tote],
    category: CATEGORIES["sustainable-shopping"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 200,
    benefits: ["Replaces 500+ plastic bags", "Machine washable", "Durable cotton canvas"],
    suitableFor: ["Daily shopping", "Grocery runs", "Gift wrapping"],
  },
  {
    name: "Bamboo Toothbrush Set of 4",
    slug: "bamboo-toothbrush-set-of-4",
    description: "Biodegradable bamboo toothbrushes with charcoal-infused bristles. Plastic-free packaging. A small switch that makes a big difference.",
    price: 299,
    discountPrice: 199,
    image: IMAGES.bamboo,
    images: [IMAGES.bamboo],
    category: CATEGORIES["sustainable-shopping"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 150,
    benefits: ["100% biodegradable handle", "Charcoal bristles for deep clean", "Plastic-free packaging"],
    suitableFor: ["All age groups", "Eco-conscious households"],
  },
  {
    name: "Seed Starter Kit — Grow Your Own Herbs",
    slug: "seed-starter-kit-grow-your-own-herbs",
    description: "Everything you need to start your kitchen garden. Includes 6 herb seed packets, coco-peat pots, and a growing guide.",
    price: 599,
    discountPrice: 449,
    image: IMAGES.seedKit,
    images: [IMAGES.seedKit],
    category: CATEGORIES["sustainable-shopping"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 80,
    benefits: ["Non-GMO seeds", "Coco-peat biodegradable pots", "Includes growing guide"],
    suitableFor: ["Beginners", "Kitchen gardening", "Balcony gardens"],
  },
  {
    name: "Reusable Beeswax Food Wraps — Set of 3",
    slug: "reusable-beeswax-food-wraps-set-of-3",
    description: "Natural beeswax wraps to replace cling film and zip-lock bags. Keeps food fresh, washable, and reusable for up to a year.",
    price: 449,
    discountPrice: 349,
    image: IMAGES.jute,
    images: [IMAGES.jute],
    category: CATEGORIES["sustainable-shopping"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 120,
    benefits: ["Replaces single-use plastic wrap", "Reusable for 1 year", "Natural beeswax coating"],
    suitableFor: ["Food storage", "Lunch boxes", "Zero-waste kitchens"],
  },
  {
    name: "Jute Shopping Bag with Zipper",
    slug: "jute-shopping-bag-with-zipper",
    description: "Sturdy jute bag with a secure zipper and inner lining. Ideal for groceries, market visits, or casual outings.",
    price: 279,
    discountPrice: 199,
    image: IMAGES.jute,
    images: [IMAGES.jute],
    category: CATEGORIES["sustainable-shopping"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 180,
  },

  // ── 2. Organic Products Online (4 products) ──────────────────────────────────
  {
    name: "Organic Vitamin C Face Serum",
    slug: "organic-vitamin-c-face-serum",
    description: "A potent 15% Vitamin C serum made with cold-pressed rosehip oil and plant-derived ingredients. Brightens skin, reduces pigmentation, and boosts collagen.",
    price: 899,
    discountPrice: 649,
    image: IMAGES.orgSerum,
    images: [IMAGES.orgSerum],
    category: CATEGORIES["organic-products-online"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 90,
    ingredients: ["Rosehip Oil", "Vitamin C (Ascorbic Acid)", "Hyaluronic Acid", "Aloe Vera"],
    benefits: ["Brightens skin tone", "Reduces dark spots", "Boosts collagen production"],
    suitableFor: ["All skin types", "Dull skin", "Hyperpigmentation"],
  },
  {
    name: "Organic Aloe Vera Face Gel",
    slug: "organic-aloe-vera-face-gel",
    description: "Pure 99% organic aloe vera gel — no fragrance, no parabens. Soothes, hydrates, and calms irritated skin.",
    price: 349,
    discountPrice: 249,
    image: IMAGES.aloeVera,
    images: [IMAGES.aloeVera],
    category: CATEGORIES["organic-products-online"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 200,
    ingredients: ["Aloe Barbadensis Leaf Extract (99%)"],
    benefits: ["Soothes sunburn", "Hydrates skin", "Calms redness"],
    suitableFor: ["Sensitive skin", "Oily skin", "After-sun care"],
  },
  {
    name: "Herbal Anti-Hairfall Shampoo",
    slug: "herbal-anti-hairfall-shampoo",
    description: "Ayurvedic shampoo with bhringraj, amla, and shikakai. Strengthens roots, reduces breakage, and promotes healthy hair growth.",
    price: 499,
    discountPrice: 379,
    image: IMAGES.herbShampoo,
    images: [IMAGES.herbShampoo],
    category: CATEGORIES["organic-products-online"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 130,
    ingredients: ["Bhringraj Extract", "Amla", "Shikakai", "Neem Oil"],
    benefits: ["Reduces hairfall", "Strengthens roots", "Adds shine"],
    suitableFor: ["All hair types", "Hairfall prone", "Sensitive scalp"],
  },
  {
    name: "Organic Neem & Tulsi Face Wash",
    slug: "organic-neem-tulsi-face-wash",
    description: "Gentle foaming face wash with neem and tulsi extracts. Controls acne, deep cleans pores, and balances oil.",
    price: 299,
    discountPrice: 219,
    image: IMAGES.orgFace,
    images: [IMAGES.orgFace],
    category: CATEGORIES["organic-products-online"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 160,
    ingredients: ["Neem Extract", "Tulsi Extract", "Tea Tree Oil", "Aloe Vera"],
    benefits: ["Controls acne", "Deep pore cleansing", "Oil balance"],
    suitableFor: ["Oily skin", "Acne-prone skin", "Combination skin"],
  },

  // ── 3. Organic Food Online (5 products) ──────────────────────────────────────
  {
    name: "Raw Forest Honey — 500g",
    slug: "raw-forest-honey-500g",
    description: "Unprocessed, unfiltered raw honey sourced from forest beehives in Uttarakhand. Rich in enzymes, antioxidants, and natural goodness.",
    price: 599,
    discountPrice: 449,
    image: IMAGES.honey,
    images: [IMAGES.honey],
    category: CATEGORIES["organic-food-online"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 100,
    benefits: ["Rich in antioxidants", "No added sugar", "Boosts immunity"],
    suitableFor: ["Daily consumption", "Tea sweetener", "Skincare"],
  },
  {
    name: "Organic Masala Chai Blend — 100g",
    slug: "organic-masala-chai-blend-100g",
    description: "A handcrafted blend of organic Assam tea, cardamom, ginger, cinnamon, and cloves. Brew a perfect cup every time.",
    price: 349,
    discountPrice: 279,
    image: IMAGES.tea,
    images: [IMAGES.tea],
    category: CATEGORIES["organic-food-online"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 200,
    ingredients: ["Organic Assam Tea", "Cardamom", "Ginger", "Cinnamon", "Cloves"],
    benefits: ["Boosts metabolism", "Warming and comforting", "No artificial flavours"],
    suitableFor: ["Tea lovers", "Morning routine", "Winter months"],
  },
  {
    name: "Cold-Pressed Coconut Oil — 500ml",
    slug: "cold-pressed-coconut-oil-500ml",
    description: "Virgin coconut oil extracted using traditional cold-press method. No heat, no chemicals — retains full nutrition for cooking, hair, and skin.",
    price: 449,
    discountPrice: 349,
    image: IMAGES.ghee,
    images: [IMAGES.ghee],
    category: CATEGORIES["organic-food-online"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 120,
    benefits: ["High smoke point for cooking", "Nourishes hair", "Moisturises skin"],
    suitableFor: ["Cooking", "Hair care", "Skin care"],
  },
  {
    name: "Organic Turmeric Powder — 200g",
    slug: "organic-turmeric-powder-200g",
    description: "Single-origin organic turmeric from Erode, Tamil Nadu. High curcumin content, naturally dried and ground. No additives.",
    price: 199,
    discountPrice: 149,
    image: IMAGES.spices,
    images: [IMAGES.spices],
    category: CATEGORIES["organic-food-online"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 300,
    benefits: ["High curcumin content", "Anti-inflammatory", "Natural colour"],
    suitableFor: ["Cooking", "Golden milk", "Face packs"],
  },
  {
    name: "Mixed Dry Fruits & Nuts Box — 500g",
    slug: "mixed-dry-fruits-nuts-box-500g",
    description: "Premium mix of almonds, cashews, raisins, pistachios, and walnuts. No added salt or sugar. Sourced from Kashmir and South India.",
    price: 799,
    discountPrice: 649,
    image: IMAGES.honey,
    images: [IMAGES.honey],
    category: CATEGORIES["organic-food-online"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 80,
    benefits: ["High protein", "Rich in healthy fats", "No preservatives"],
    suitableFor: ["Daily snacking", "Kids tiffin", "Gifting"],
  },

  // ── 4. Chemical-Free Products (3 products) ────────────────────────────────────
  {
    name: "Chemical-Free Charcoal Face Cleanser",
    slug: "chemical-free-charcoal-face-cleanser",
    description: "A 100% chemical-free cleanser with activated charcoal and kaolin clay. Draws out impurities without stripping natural oils.",
    price: 399,
    discountPrice: 299,
    image: IMAGES.cleanser,
    images: [IMAGES.cleanser],
    category: CATEGORIES["chemical-free-products"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 110,
    ingredients: ["Activated Charcoal", "Kaolin Clay", "Tea Tree Oil", "Aloe Vera"],
    benefits: ["Deep pore cleansing", "No harsh chemicals", "Balances oil"],
    suitableFor: ["Oily skin", "Acne-prone skin", "All skin types"],
  },
  {
    name: "Natural Fluoride-Free Toothpaste",
    slug: "natural-fluoride-free-toothpaste",
    description: "Ayurvedic toothpaste with neem, clove, and mint. No fluoride, no SLS, no artificial colours. Gentle on enamel, tough on bacteria.",
    price: 249,
    discountPrice: 179,
    image: IMAGES.toothpaste,
    images: [IMAGES.toothpaste],
    category: CATEGORIES["chemical-free-products"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 220,
    ingredients: ["Neem Extract", "Clove Oil", "Mint", "Calcium Carbonate"],
    benefits: ["No fluoride", "Antibacterial", "Fresh breath"],
    suitableFor: ["Adults", "Children above 6", "Sensitive gums"],
  },
  {
    name: "Aluminium-Free Natural Deodorant",
    slug: "aluminium-free-natural-deodorant",
    description: "Baking soda and coconut oil based deodorant. No aluminium, no parabens. Keeps you fresh for 8–10 hours naturally.",
    price: 349,
    discountPrice: 279,
    image: IMAGES.deodorant,
    images: [IMAGES.deodorant],
    category: CATEGORIES["chemical-free-products"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 140,
    ingredients: ["Baking Soda", "Coconut Oil", "Shea Butter", "Lavender Essential Oil"],
    benefits: ["No aluminium salts", "8-10 hour freshness", "Skin-safe formula"],
    suitableFor: ["Sensitive skin", "Daily use", "Active lifestyle"],
  },

  // ── 5. Artisan Products (4 products) ──────────────────────────────────────────
  {
    name: "Handpainted Blue Pottery Mug",
    slug: "handpainted-blue-pottery-mug",
    description: "Traditional Jaipur blue pottery mug, hand-painted by local artisans. Each piece is unique. Holds 250ml. Food-safe glaze.",
    price: 599,
    discountPrice: 449,
    image: IMAGES.pottery,
    images: [IMAGES.pottery],
    category: CATEGORIES["artisan-products"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 60,
    benefits: ["Unique handpainted design", "Food-safe glaze", "Supports local artisans"],
    suitableFor: ["Tea and coffee", "Home decor", "Gifting"],
  },
  {
    name: "Block Print Cotton Cushion Cover",
    slug: "block-print-cotton-cushion-cover",
    description: "Hand block-printed cushion cover from Sanganer, Rajasthan. Natural dyes, 100% cotton. 16x16 inch.",
    price: 449,
    discountPrice: 329,
    image: IMAGES.blockPrint,
    images: [IMAGES.blockPrint],
    category: CATEGORIES["artisan-products"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 90,
    benefits: ["Natural vegetable dyes", "Hand block-printed", "100% cotton"],
    suitableFor: ["Home decor", "Gifting", "Sofa and bed styling"],
  },
  {
    name: "Madhubani Art Wall Frame — A4",
    slug: "madhubani-art-wall-frame-a4",
    description: "Original Madhubani painting on handmade paper, framed in natural wood. Artwork by certified artisans from Mithila, Bihar.",
    price: 1299,
    discountPrice: 999,
    image: IMAGES.woodArt,
    images: [IMAGES.woodArt],
    category: CATEGORIES["artisan-products"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 30,
    benefits: ["Original artwork", "Natural wood frame", "Certificate of authenticity"],
    suitableFor: ["Wall decor", "Gifting", "Office and home"],
  },
  {
    name: "Terracotta Hanging Planter — Set of 2",
    slug: "terracotta-hanging-planter-set-of-2",
    description: "Handcrafted terracotta planters with macrame hangers. Ideal for succulents, small herbs, or trailing plants.",
    price: 699,
    discountPrice: 549,
    image: IMAGES.pottery,
    images: [IMAGES.pottery],
    category: CATEGORIES["artisan-products"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 70,
    benefits: ["Breathable terracotta", "Handcrafted", "With macrame hanger"],
    suitableFor: ["Balcony gardens", "Indoor plants", "Home decor"],
  },

  // ── 6. Eco-Friendly Products (3 products) ────────────────────────────────────
  {
    name: "Bamboo Drinking Straws — Pack of 12",
    slug: "bamboo-drinking-straws-pack-of-12",
    description: "Reusable bamboo straws with a cleaning brush. Natural, biodegradable, and chemical-free alternative to plastic straws.",
    price: 249,
    discountPrice: 179,
    image: IMAGES.bambooStraw,
    images: [IMAGES.bambooStraw],
    category: CATEGORIES["eco-friendly-products"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 250,
    benefits: ["Plastic-free", "Includes cleaning brush", "Biodegradable"],
    suitableFor: ["Home use", "Cafes", "Kids drinks"],
  },
  {
    name: "Recycled Newspaper Gift Bags — Set of 6",
    slug: "recycled-newspaper-gift-bags-set-of-6",
    description: "Beautifully crafted gift bags made from recycled newspapers. Strong, stylish, and 100% plastic-free.",
    price: 199,
    discountPrice: 149,
    image: IMAGES.jute,
    images: [IMAGES.jute],
    category: CATEGORIES["eco-friendly-products"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 300,
    benefits: ["100% recycled material", "Plastic-free", "Unique patterns"],
    suitableFor: ["Gifting", "Party favours", "Festive packaging"],
  },
  {
    name: "Natural Loofah Bath Scrubber",
    slug: "natural-loofah-bath-scrubber",
    description: "100% natural dried loofah — grown and harvested in India. Exfoliates skin naturally and decomposes completely after use.",
    price: 149,
    discountPrice: 99,
    image: IMAGES.soapBar,
    images: [IMAGES.soapBar],
    category: CATEGORIES["eco-friendly-products"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 400,
    benefits: ["Natural exfoliant", "100% biodegradable", "Plastic-free bath routine"],
    suitableFor: ["All skin types", "Daily bathing", "Eco-conscious living"],
  },

  // ── 7. Natural Products (3 products) ──────────────────────────────────────────
  {
    name: "Pure Lavender Essential Oil — 15ml",
    slug: "pure-lavender-essential-oil-15ml",
    description: "Steam-distilled pure lavender essential oil. Calming, soothing, and versatile — for aromatherapy, diffusers, and DIY skincare.",
    price: 499,
    discountPrice: 379,
    image: IMAGES.essOil,
    images: [IMAGES.essOil],
    category: CATEGORIES["natural-products"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 100,
    benefits: ["100% pure, no fillers", "Promotes relaxation", "Versatile use"],
    suitableFor: ["Aromatherapy", "Diffusers", "DIY skincare"],
  },
  {
    name: "Neem & Charcoal Detox Soap Bar",
    slug: "neem-charcoal-detox-soap-bar",
    description: "Cold-process soap with activated charcoal, neem oil, and tea tree. Deep cleanses, detoxifies, and controls acne.",
    price: 199,
    discountPrice: 149,
    image: IMAGES.soapBar,
    images: [IMAGES.soapBar],
    category: CATEGORIES["natural-products"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 200,
    ingredients: ["Activated Charcoal", "Neem Oil", "Tea Tree Oil", "Coconut Oil"],
    benefits: ["Detoxifies skin", "Controls acne", "No SLS or parabens"],
    suitableFor: ["Oily skin", "Acne-prone skin", "Daily use"],
  },
  {
    name: "Rose & Sandalwood Body Butter",
    slug: "rose-sandalwood-body-butter",
    description: "Rich body butter with shea, cocoa butter, rose essential oil, and sandalwood. Deeply nourishes and leaves skin silky smooth.",
    price: 549,
    discountPrice: 399,
    image: IMAGES.orgSerum,
    images: [IMAGES.orgSerum],
    category: CATEGORIES["natural-products"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 80,
    ingredients: ["Shea Butter", "Cocoa Butter", "Rose Essential Oil", "Sandalwood Oil"],
    benefits: ["Deep moisturisation", "Long-lasting fragrance", "No mineral oil"],
    suitableFor: ["Dry skin", "Post-shower", "Body massage"],
  },

  // ── 8. Handmade Crafts (4 products) ───────────────────────────────────────────
  {
    name: "Macrame Wall Hanging — Boho Style",
    slug: "macrame-wall-hanging-boho-style",
    description: "Handcrafted macrame wall hanging made with natural cotton cord. Bohemian aesthetic, perfect for living rooms and bedrooms.",
    price: 899,
    discountPrice: 699,
    image: IMAGES.macrame,
    images: [IMAGES.macrame],
    category: CATEGORIES["handmade-crafts"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 40,
    benefits: ["Handcrafted", "Natural cotton cord", "Unique boho design"],
    suitableFor: ["Living room decor", "Bedroom walls", "Gifting"],
  },
  {
    name: "Handmade Soy Wax Candle — Vanilla",
    slug: "handmade-soy-wax-candle-vanilla",
    description: "Pure soy wax candle with natural vanilla fragrance. Cotton wick, no paraffin, burns clean for 40+ hours.",
    price: 399,
    discountPrice: 299,
    image: IMAGES.candle,
    images: [IMAGES.candle],
    category: CATEGORIES["handmade-crafts"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 120,
    benefits: ["40+ hour burn time", "No paraffin or toxins", "Natural cotton wick"],
    suitableFor: ["Home ambiance", "Gifting", "Meditation and yoga"],
  },
  {
    name: "Hand-Embroidered Coin Purse",
    slug: "hand-embroidered-coin-purse",
    description: "Colourful hand-embroidered coin purse from Kutch, Gujarat. Traditional mirror work, zip closure, and cotton lining.",
    price: 299,
    discountPrice: 219,
    image: IMAGES.embroidery,
    images: [IMAGES.embroidery],
    category: CATEGORIES["handmade-crafts"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 80,
    benefits: ["Traditional Kutch embroidery", "Mirror work detailing", "Supports artisan women"],
    suitableFor: ["Daily use", "Gifting", "Festive accessory"],
  },
  {
    name: "Resin Art Coasters — Set of 4",
    slug: "resin-art-coasters-set-of-4",
    description: "Handcrafted resin coasters with pressed flowers and gold foil. Each set is unique. Heat and water resistant.",
    price: 599,
    discountPrice: 449,
    image: IMAGES.woodArt,
    images: [IMAGES.woodArt],
    category: CATEGORIES["handmade-crafts"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 50,
    benefits: ["Heat resistant", "Waterproof", "Unique pressed flower design"],
    suitableFor: ["Home decor", "Gifting", "Office desk"],
  },

  // ── 9. Handmade Products (4 products) ─────────────────────────────────────────
  {
    name: "Handmade Lavender Goat Milk Soap",
    slug: "handmade-lavender-goat-milk-soap",
    description: "Cold-process soap made with goat milk, lavender oil, and oat flour. Gentle, moisturising, and suitable for sensitive skin.",
    price: 249,
    discountPrice: 179,
    image: IMAGES.soapBar,
    images: [IMAGES.soapBar],
    category: CATEGORIES["handmade-products"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 150,
    ingredients: ["Goat Milk", "Lavender Essential Oil", "Oat Flour", "Coconut Oil"],
    benefits: ["Gentle on sensitive skin", "Natural moisturiser", "Calming fragrance"],
    suitableFor: ["Sensitive skin", "Dry skin", "Daily bathing"],
  },
  {
    name: "Handmade Beaded Bracelet — Boho",
    slug: "handmade-beaded-bracelet-boho",
    description: "Hand-strung bracelet with natural stone beads — amethyst, lapis, and turquoise. Adjustable cord closure. Each piece is one-of-a-kind.",
    price: 349,
    discountPrice: 249,
    image: IMAGES.jewelry,
    images: [IMAGES.jewelry],
    category: CATEGORIES["handmade-products"],
    shopId: SHOPS.bhavya,
    origin: "made-in-india",
    stock: 70,
    benefits: ["Natural stone beads", "Adjustable size", "Unique handstrung design"],
    suitableFor: ["Daily wear", "Gifting", "Festive styling"],
  },
  {
    name: "Home Made Rose & Honey Face Pack — 100g",
    slug: "home-made-rose-honey-face-pack-100g",
    description: "Freshly made face pack with dried rose petals, raw honey, and multani mitti. No preservatives — made in small batches.",
    price: 299,
    discountPrice: 219,
    image: IMAGES.orgFace,
    images: [IMAGES.orgFace],
    category: CATEGORIES["handmade-products"],
    shopId: SHOPS.varun,
    origin: "made-in-india",
    stock: 60,
    ingredients: ["Dried Rose Petals", "Raw Honey", "Multani Mitti", "Sandalwood Powder"],
    benefits: ["Brightens complexion", "Deep cleanses pores", "No preservatives"],
    suitableFor: ["All skin types", "Weekly skincare ritual"],
  },
  {
    name: "Handmade Crochet Plant Hanger",
    slug: "handmade-crochet-plant-hanger",
    description: "Hand-crocheted plant hanger in natural cotton. Holds pots up to 6 inch. Adds a cosy, handmade touch to your space.",
    price: 399,
    discountPrice: 299,
    image: IMAGES.macrame,
    images: [IMAGES.macrame],
    category: CATEGORIES["handmade-products"],
    shopId: SHOPS.mihir,
    origin: "made-in-india",
    stock: 55,
    benefits: ["Hand crocheted", "Natural cotton", "Holds 6 inch pots"],
    suitableFor: ["Indoor plants", "Balcony decor", "Gifting"],
  },
];

// ── Mongoose setup ────────────────────────────────────────────────────────────
async function run() {
  if (!MONGODB_URI) {
    console.error("❌ MONGODB_URI not found in .env.local");
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log("✅ Connected to MongoDB");

  // Dynamically import models (avoids Next.js module issues)
  const { Product } = await import("../models/product");
  await import("../models/shop");
  await import("../models/category");

  let created = 0;
  let skipped = 0;

  for (const p of SEED_PRODUCTS) {
    const existing = await Product.findOne({ slug: p.slug });
    if (existing) {
      console.log(`⏭  Skipped (already exists): ${p.name}`);
      skipped++;
      continue;
    }

    await Product.create({
      ...p,
      approvalStatus: "approved",
      isActive: true,
      submittedAt: new Date(),
      approvedAt: new Date(),
    });

    console.log(`✅ Created: ${p.name}`);
    created++;
  }

  console.log(`\n🎉 Done! Created: ${created} | Skipped: ${skipped} | Total: ${SEED_PRODUCTS.length}`);
  await mongoose.disconnect();
  process.exit(0);
}

run().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});